[package]
name = "nadac_top10"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.88"
csv = "1.3.0"
reqwest = "0.12.7"
rust_decimal = "1.36.0"
serde = { version = "1", features = ["derive", "serde_derive"] }
tokio = {version = "1.39.3", features = ["full", "rt-multi-thread"]}