[package]
name = "hello_solana"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
solana-program = "2.0.9"

[dev-dependencies]
solana-program-test = "2.0.9"
solana-sdk = "2.0.9"

[lib]
name = "hello_solana"
crate-type = ["cdylib", "lib"]
